version: '3.8'

services:
  yolov12-api:
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: yolov12-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app
    command: python main.py
    # Uncomment untuk GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
